using System.Collections.Generic;
using GTANetworkAPI;
using NeptuneEvo.Handles;
using NeptuneEvo.VehicleModel.Models;
using NeptuneEvo.Chars;
using Redage.SDK;
using System;

namespace NeptuneEvo.VehicleModel
{
    class vMain : Script
    {
		private static readonly nLog Log = new nLog("VehicleModel.Main");

		public static readonly Dictionary<uint, VehicleInfo> VehicleData = new Dictionary<uint, VehicleInfo>()
        {
			{ NAPI.Util.GetHashKey("Faggio2"), new VehicleInfo("Motoroom", 3, 250)},
			{ NAPI.Util.GetHashKey("Verus"), new VehicleInfo("Motoroom", 5, 17500)},
			{ NAPI.Util.GetHashKey("Sanchez2"), new VehicleInfo("Motoroom", 5, 1750)},
			{ NAPI.Util.GetHashKey("Enduro"), new VehicleInfo("Motoroom", 5, 2000)},
			{ NAPI.Util.GetHashKey("PCJ"), new VehicleInfo("Motoroom", 5, 3250)},
			{ NAPI.Util.GetHashKey("Hexer"), new VehicleInfo("Motoroom", 5, 3500)},
			{ NAPI.Util.GetHashKey("Lectro"), new VehicleInfo("Motoroom", 5, 3750)},
			{ NAPI.Util.GetHashKey("Nemesis"), new VehicleInfo("Motoroom", 5, 3750)},
			{ NAPI.Util.GetHashKey("Hakuchou"), new VehicleInfo("Motoroom", 5, 4250)},
			{ NAPI.Util.GetHashKey("Ruffian"), new VehicleInfo("Motoroom", 5, 4750)},
			{ NAPI.Util.GetHashKey("Bmx"), new VehicleInfo("Motoroom", 0, 800)},
			{ NAPI.Util.GetHashKey("Scorcher"), new VehicleInfo("Motoroom", 0, 1200)},
			{ NAPI.Util.GetHashKey("BF400"), new VehicleInfo("Motoroom", 5, 5000)},
			{ NAPI.Util.GetHashKey("CarbonRS"), new VehicleInfo("Motoroom", 5, 5750)},
			{ NAPI.Util.GetHashKey("Bati"), new VehicleInfo("Motoroom", 5, 7000)},
			{ NAPI.Util.GetHashKey("Double"), new VehicleInfo("Motoroom", 5, 7500)},
			{ NAPI.Util.GetHashKey("Diablous"), new VehicleInfo("Motoroom", 5, 10000)},
			{ NAPI.Util.GetHashKey("Cliffhanger"), new VehicleInfo("Motoroom", 5, 11250)},
			{ NAPI.Util.GetHashKey("Akuma"), new VehicleInfo("Motoroom", 5, 13750)},
			{ NAPI.Util.GetHashKey("Thrust"), new VehicleInfo("Motoroom", 5, 16500)},
			{ NAPI.Util.GetHashKey("Nightblade"), new VehicleInfo("Motoroom", 5, 6000)},
			{ NAPI.Util.GetHashKey("Vindicator"), new VehicleInfo("Motoroom", 6, 8500)},
			{ NAPI.Util.GetHashKey("Ratbike"), new VehicleInfo("Motoroom", 5, 4500)},
			{ NAPI.Util.GetHashKey("Blazer"), new VehicleInfo("Motoroom", 7, 5200)},
			{ NAPI.Util.GetHashKey("Gargoyle"), new VehicleInfo("Motoroom", 5, 6800)},
			{ NAPI.Util.GetHashKey("Sanctus"), new VehicleInfo("Motoroom", 5, 500000)},
			{ NAPI.Util.GetHashKey("Bagger"), new VehicleInfo("Motoroom", 6, 2200)},
			{ NAPI.Util.GetHashKey("Diablous2"), new VehicleInfo("Motoroom", 5, 5600)},
			{ NAPI.Util.GetHashKey("Sovereign"), new VehicleInfo("Motoroom", 6, 2100)},
			{ NAPI.Util.GetHashKey("Avarus"), new VehicleInfo("Motoroom", 5, 4800)},
			{ NAPI.Util.GetHashKey("Bati2"), new VehicleInfo("Motoroom", 5, 7000)},
			{ NAPI.Util.GetHashKey("Daemon"), new VehicleInfo("Motoroom", 5, 4800)},
			{ NAPI.Util.GetHashKey("Daemon2"), new VehicleInfo("Motoroom", 5, 4700)},
			{ NAPI.Util.GetHashKey("Defiler"), new VehicleInfo("Motoroom", 5, 6000)},
			{ NAPI.Util.GetHashKey("Vortex"), new VehicleInfo("Motoroom", 5, 5800)},
			{ NAPI.Util.GetHashKey("Vader"), new VehicleInfo("Motoroom", 5, 4950)},
			{ NAPI.Util.GetHashKey("Esskey"), new VehicleInfo("Motoroom", 5, 4000)},
			{ NAPI.Util.GetHashKey("Faggio"), new VehicleInfo("Motoroom", 3, 260)},
			{ NAPI.Util.GetHashKey("Faggio3"), new VehicleInfo("Motoroom", 3, 300)},
			{ NAPI.Util.GetHashKey("Manchez"), new VehicleInfo("Motoroom", 5, 1900)},
			{ NAPI.Util.GetHashKey("Wolfsbane"), new VehicleInfo("Motoroom", 5, 4800)},
			{ NAPI.Util.GetHashKey("Zombiea"), new VehicleInfo("Motoroom", 5, 5000)},
			{ NAPI.Util.GetHashKey("Zombieb"), new VehicleInfo("Motoroom", 5, 5100)},
			{ NAPI.Util.GetHashKey("Blazer4"), new VehicleInfo("Motoroom", 7, 5800)},
			{ NAPI.Util.GetHashKey("Deathbike"), new VehicleInfo("Motoroom", 5, 14000)},
			{ NAPI.Util.GetHashKey("Fcr"), new VehicleInfo("Motoroom", 5, 6000)},
			{ NAPI.Util.GetHashKey("Fcr2"), new VehicleInfo("Motoroom", 5, 7000)},
			{ NAPI.Util.GetHashKey("Hakuchou2"), new VehicleInfo("Motoroom", 5, 18000)},
			{ NAPI.Util.GetHashKey("Innovation"), new VehicleInfo("Motoroom", 5, 25000)},
			{ NAPI.Util.GetHashKey("Stryder"), new VehicleInfo("Motoroom", 7, 20000)},
			{ NAPI.Util.GetHashKey("Fixter"), new VehicleInfo("Motoroom", 0, 1000)},
			{ NAPI.Util.GetHashKey("Cruiser"), new VehicleInfo("Motoroom", 0, 1200)},
			{ NAPI.Util.GetHashKey("Tribike"), new VehicleInfo("Motoroom", 0, 1500)},
			{ NAPI.Util.GetHashKey("Tribike2"), new VehicleInfo("Motoroom", 0, 1500)},
			{ NAPI.Util.GetHashKey("Tribike3"), new VehicleInfo("Motoroom", 0, 1500)},
			{ NAPI.Util.GetHashKey("Blazer3"), new VehicleInfo("Motoroom", 7, 8000)},
			{ NAPI.Util.GetHashKey("Tornado3"), new VehicleInfo("Low Autoroom", 15, 750)},
			{ NAPI.Util.GetHashKey("Tornado4"), new VehicleInfo("Low Autoroom", 15, 800)},
			{ NAPI.Util.GetHashKey("Emperor2"), new VehicleInfo("Low Autoroom", 20, 800)},
			{ NAPI.Util.GetHashKey("Voodoo2"), new VehicleInfo("Low Autoroom", 15, 825)},
			{ NAPI.Util.GetHashKey("Regina"), new VehicleInfo("Low Autoroom", 30, 850)},
			{ NAPI.Util.GetHashKey("Ingot"), new VehicleInfo("Low Autoroom", 30, 875)},
			{ NAPI.Util.GetHashKey("Emperor"), new VehicleInfo("Low Autoroom", 20, 2000)},
			{ NAPI.Util.GetHashKey("Picador"), new VehicleInfo("Low Autoroom", 25, 2250)},
			{ NAPI.Util.GetHashKey("Minivan"), new VehicleInfo("Low Autoroom", 35, 2000)},
			{ NAPI.Util.GetHashKey("Blista2"), new VehicleInfo("Low Autoroom", 15, 2250)},
			{ NAPI.Util.GetHashKey("Manana"), new VehicleInfo("Low Autoroom", 15, 2250)},
			{ NAPI.Util.GetHashKey("Dilettante"), new VehicleInfo("Low Autoroom", 25, 2500)},
			{ NAPI.Util.GetHashKey("Asea"), new VehicleInfo("Low Autoroom", 25, 2500)},
			{ NAPI.Util.GetHashKey("Glendale"), new VehicleInfo("Low Autoroom", 25, 3250)},
			{ NAPI.Util.GetHashKey("Voodoo"), new VehicleInfo("Low Autoroom", 15, 2500)},
			{ NAPI.Util.GetHashKey("Surge"), new VehicleInfo("Low Autoroom", 25, 3250)},
			{ NAPI.Util.GetHashKey("Primo"), new VehicleInfo("Low Autoroom", 25, 3370)},
			{ NAPI.Util.GetHashKey("Stanier"), new VehicleInfo("Low Autoroom", 25, 3500)},
			{ NAPI.Util.GetHashKey("Stratum"), new VehicleInfo("Low Autoroom", 30, 3750)},
			{ NAPI.Util.GetHashKey("Tampa"), new VehicleInfo("Low Autoroom", 15, 3875)},
			{ NAPI.Util.GetHashKey("Prairie"), new VehicleInfo("Low Autoroom", 15, 3950)},
			{ NAPI.Util.GetHashKey("Radi"), new VehicleInfo("Low Autoroom", 35, 3900)},
			{ NAPI.Util.GetHashKey("Blista"), new VehicleInfo("Low Autoroom", 15, 4150)},
			{ NAPI.Util.GetHashKey("Stalion"), new VehicleInfo("Low Autoroom", 15, 4250)},
			{ NAPI.Util.GetHashKey("Asterope"), new VehicleInfo("Low Autoroom", 25, 4700)},
			{ NAPI.Util.GetHashKey("Washington"), new VehicleInfo("Low Autoroom", 25, 4975)},
			{ NAPI.Util.GetHashKey("Premier"), new VehicleInfo("Low Autoroom", 25, 5000)},
			{ NAPI.Util.GetHashKey("Intruder"), new VehicleInfo("Low Autoroom", 25, 4500)},
			{ NAPI.Util.GetHashKey("Ruiner"), new VehicleInfo("Low Autoroom", 15, 5000)},
			{ NAPI.Util.GetHashKey("Oracle"), new VehicleInfo("Low Autoroom", 25, 5250)},
			{ NAPI.Util.GetHashKey("Phoenix"), new VehicleInfo("Low Autoroom", 15, 6250)},
			{ NAPI.Util.GetHashKey("Gauntlet"), new VehicleInfo("Low Autoroom", 15, 7000)},
			{ NAPI.Util.GetHashKey("Buffalo"), new VehicleInfo("Low Autoroom", 25, 7000)},
			{ NAPI.Util.GetHashKey("RancherXL"), new VehicleInfo("Low Autoroom", 45, 3750)},
			{ NAPI.Util.GetHashKey("Seminole"), new VehicleInfo("Low Autoroom", 35, 5000)},
			{ NAPI.Util.GetHashKey("Baller"), new VehicleInfo("Low Autoroom", 35, 12500)},
			{ NAPI.Util.GetHashKey("Landstalker"), new VehicleInfo("Low Autoroom", 35, 13750)},
			{ NAPI.Util.GetHashKey("Cavalcade"), new VehicleInfo("Low Autoroom", 35, 15000)},
			{ NAPI.Util.GetHashKey("BJXL"), new VehicleInfo("Low Autoroom", 35, 15250)},
			{ NAPI.Util.GetHashKey("Patriot"), new VehicleInfo("Low Autoroom", 35, 17500)},
			{ NAPI.Util.GetHashKey("Bison3"), new VehicleInfo("Low Autoroom", 35, 7500)},
			{ NAPI.Util.GetHashKey("Issi2"), new VehicleInfo("Low Autoroom", 15, 8500)},
			{ NAPI.Util.GetHashKey("Panto"), new VehicleInfo("Low Autoroom", 15, 4500)},
			{ NAPI.Util.GetHashKey("Rhapsody"), new VehicleInfo("Low Autoroom", 15, 1000)},
			{ NAPI.Util.GetHashKey("Buccaneer2"), new VehicleInfo("Low Autoroom", 15, 3600)},
			{ NAPI.Util.GetHashKey("Dukes"), new VehicleInfo("Low Autoroom", 15, 3800)},
			{ NAPI.Util.GetHashKey("Faction"), new VehicleInfo("Low Autoroom", 15, 3000)},
			{ NAPI.Util.GetHashKey("Faction2"), new VehicleInfo("Low Autoroom", 15, 3800)},
			{ NAPI.Util.GetHashKey("Hermes"), new VehicleInfo("Low Autoroom", 15, 1200)},
			{ NAPI.Util.GetHashKey("Moonbeam2"), new VehicleInfo("Low Autoroom", 45, 6400)},
			{ NAPI.Util.GetHashKey("Futo"), new VehicleInfo("Low Autoroom", 15, 6200)},
			{ NAPI.Util.GetHashKey("Blade"), new VehicleInfo("Low Autoroom", 15, 3400)},
			{ NAPI.Util.GetHashKey("Chino"), new VehicleInfo("Low Autoroom", 15, 2200)},
			{ NAPI.Util.GetHashKey("Chino2"), new VehicleInfo("Low Autoroom", 15, 3000)},
			{ NAPI.Util.GetHashKey("Gauntlet2"), new VehicleInfo("Low Autoroom", 15, 7000)},
			{ NAPI.Util.GetHashKey("Sabregt"), new VehicleInfo("Low Autoroom", 15, 6000)},
			{ NAPI.Util.GetHashKey("Sabregt2"), new VehicleInfo("Low Autoroom", 15, 6900)},
			{ NAPI.Util.GetHashKey("Stalion2"), new VehicleInfo("Low Autoroom", 15, 4250)},
			{ NAPI.Util.GetHashKey("Bfinjection"), new VehicleInfo("Low Autoroom", 15, 2300)},
			{ NAPI.Util.GetHashKey("Bodhi2"), new VehicleInfo("Low Autoroom", 40, 4000)},
			{ NAPI.Util.GetHashKey("Rebel"), new VehicleInfo("Low Autoroom", 40, 4900)},
			{ NAPI.Util.GetHashKey("Rebel2"), new VehicleInfo("Low Autoroom", 40, 5000)},
			{ NAPI.Util.GetHashKey("Primo2"), new VehicleInfo("Low Autoroom", 25, 4300)},
			{ NAPI.Util.GetHashKey("Warrener"), new VehicleInfo("Low Autoroom", 25, 3700)},
			{ NAPI.Util.GetHashKey("Buffalo2"), new VehicleInfo("Low Autoroom", 25, 8200)},
			{ NAPI.Util.GetHashKey("Slamvan"), new VehicleInfo("Low Autoroom", 40, 4500)},
			{ NAPI.Util.GetHashKey("Virgo"), new VehicleInfo("Low Autoroom", 15, 2000)},
			{ NAPI.Util.GetHashKey("Virgo2"), new VehicleInfo("Low Autoroom", 15, 2400)},
			{ NAPI.Util.GetHashKey("Virgo3"), new VehicleInfo("Low Autoroom", 15, 2410)},
			{ NAPI.Util.GetHashKey("Blista3"), new VehicleInfo("Low Autoroom", 15, 4300)},
			{ NAPI.Util.GetHashKey("Buffalo3"), new VehicleInfo("Low Autoroom", 25, 8200)},
			{ NAPI.Util.GetHashKey("Peyote"), new VehicleInfo("Low Autoroom", 15, 2900)},
			{ NAPI.Util.GetHashKey("Retinue"), new VehicleInfo("Low Autoroom", 25, 5600)},
			{ NAPI.Util.GetHashKey("Savestra"), new VehicleInfo("Low Autoroom", 25, 5700)},
			{ NAPI.Util.GetHashKey("Tornado"), new VehicleInfo("Low Autoroom", 15, 700)},
			{ NAPI.Util.GetHashKey("Tornado2"), new VehicleInfo("Low Autoroom", 15, 740)},
			{ NAPI.Util.GetHashKey("Brioso2"), new VehicleInfo("Low Autoroom", 15, 3500)},
			{ NAPI.Util.GetHashKey("Weevil"), new VehicleInfo("Low Autoroom", 15, 4000)},
			{ NAPI.Util.GetHashKey("Tornado5"), new VehicleInfo("Low Autoroom", 15, 950)},
			{ NAPI.Util.GetHashKey("Brioso"), new VehicleInfo("Low Autoroom", 15, 4800)},
			{ NAPI.Util.GetHashKey("Issi3"), new VehicleInfo("Low Autoroom", 15, 3200)},
			{ NAPI.Util.GetHashKey("Tulip"), new VehicleInfo("Low Autoroom", 15, 7500)},
			{ NAPI.Util.GetHashKey("Vamos"), new VehicleInfo("Low Autoroom", 15, 7800)},
			{ NAPI.Util.GetHashKey("Hellion"), new VehicleInfo("Low Autoroom", 35, 16000)},
			{ NAPI.Util.GetHashKey("Nebula"), new VehicleInfo("Low Autoroom", 25, 3700)},
			{ NAPI.Util.GetHashKey("Cheburek"), new VehicleInfo("Low Autoroom", 25, 25000)},
			{ NAPI.Util.GetHashKey("Zion3"), new VehicleInfo("Low Autoroom", 15, 19000)},
			{ NAPI.Util.GetHashKey("Gauntlet3"), new VehicleInfo("Low Autoroom", 15, 9500)},
			{ NAPI.Util.GetHashKey("Imperator"), new VehicleInfo("Low Autoroom", 15, 9000)},
			{ NAPI.Util.GetHashKey("Habanero"), new VehicleInfo("Low Autoroom", 30, 6100)},
			{ NAPI.Util.GetHashKey("Ellie"), new VehicleInfo("Low Autoroom", 15, 11000)},
			{ NAPI.Util.GetHashKey("Retinue2"), new VehicleInfo("Low Autoroom", 25, 5500)},
			{ NAPI.Util.GetHashKey("Yosemite2"), new VehicleInfo("Low Autoroom", 40, 4600)},
			{ NAPI.Util.GetHashKey("Asbo"), new VehicleInfo("Low Autoroom", 15, 4800)},
			{ NAPI.Util.GetHashKey("Kanjo"), new VehicleInfo("Low Autoroom", 15, 5200)},
			{ NAPI.Util.GetHashKey("Clique"), new VehicleInfo("Low Autoroom", 15, 2000)},
			{ NAPI.Util.GetHashKey("Ratloader2"), new VehicleInfo("Low Autoroom", 40, 8000)},
			{ NAPI.Util.GetHashKey("Yosemite"), new VehicleInfo("Low Autoroom", 40, 2500)},
			{ NAPI.Util.GetHashKey("Dloader"), new VehicleInfo("Low Autoroom", 45, 3000)},
			{ NAPI.Util.GetHashKey("Dynasty"), new VehicleInfo("Low Autoroom", 25, 2000)},
			{ NAPI.Util.GetHashKey("Fagaloa"), new VehicleInfo("Low Autoroom", 30, 1500)},
			{ NAPI.Util.GetHashKey("Club"), new VehicleInfo("Low Autoroom", 25, 5400)},
			{ NAPI.Util.GetHashKey("Dukes3"), new VehicleInfo("Low Autoroom", 15, 5800)},
			{ NAPI.Util.GetHashKey("Glendale2"), new VehicleInfo("Low Autoroom", 25, 4250)},
			{ NAPI.Util.GetHashKey("Peyote3"), new VehicleInfo("Low Autoroom", 15, 5900)},
			{ NAPI.Util.GetHashKey("Manana2"), new VehicleInfo("Low Autoroom", 15, 2460)},

			{ NAPI.Util.GetHashKey("warrener2"), new VehicleInfo("Low Autoroom", 35, 4400)},
			{ NAPI.Util.GetHashKey("previon"), new VehicleInfo("Low Autoroom", 15, 6800)},
			{ NAPI.Util.GetHashKey("remus"), new VehicleInfo("Low Autoroom", 15, 7400)},
			{ NAPI.Util.GetHashKey("futo2"), new VehicleInfo("Low Autoroom", 15, 7600)},
			{ NAPI.Util.GetHashKey("dominator8"), new VehicleInfo("Low Autoroom", 15, 14000)},

			{ NAPI.Util.GetHashKey("niva"), new VehicleInfo("Luxor Autoroom", 15, 44200)},
			{ NAPI.Util.GetHashKey("ffastback66"), new VehicleInfo("Luxor Autoroom", 15, 43200)},
			{ NAPI.Util.GetHashKey("fmustang95"), new VehicleInfo("Luxor Autoroom", 15, 45500)},
			{ NAPI.Util.GetHashKey("lc100"), new VehicleInfo("Luxor Autoroom", 15, 46000)},
			{ NAPI.Util.GetHashKey("civic6"), new VehicleInfo("Luxor Autoroom", 15, 49000)},
			{ NAPI.Util.GetHashKey("lincoln"), new VehicleInfo("Luxor Autoroom", 15, 38500)},
			{ NAPI.Util.GetHashKey("oka"), new VehicleInfo("Luxor Autoroom", 5, 475000)},
			{ NAPI.Util.GetHashKey("vesta"), new VehicleInfo("Luxor Autoroom", 15, 46500)},
			{ NAPI.Util.GetHashKey("eclipse"), new VehicleInfo("Luxor Autoroom", 10, 48500)},
			{ NAPI.Util.GetHashKey("mk7"), new VehicleInfo("Luxor Autoroom", 35, 41000)},

			{ NAPI.Util.GetHashKey("m2"), new VehicleInfo("Premium Autoroom", 35, 1400000, "m2")},
			{ NAPI.Util.GetHashKey("supra2020"), new VehicleInfo("Premium Autoroom", 15, 1350000, "supra 2020")},
			{ NAPI.Util.GetHashKey("ttrs"), new VehicleInfo("Premium Autoroom", 25, 1500000, "tt rs")},
			{ NAPI.Util.GetHashKey("z350"), new VehicleInfo("Premium Autoroom", 15, 1575000, "350 z")},
			{ NAPI.Util.GetHashKey("7e38"), new VehicleInfo("Premium Autoroom", 15, 1450000, "7 e38")},
			{ NAPI.Util.GetHashKey("amggtvp"), new VehicleInfo("Premium Autoroom", 35, 1600000, "amg gt")},
			{ NAPI.Util.GetHashKey("bacalar"), new VehicleInfo("Premium Autoroom", 15, 1585000, "bacalar")},
			{ NAPI.Util.GetHashKey("camry19"), new VehicleInfo("Premium Autoroom", 15, 1550000, "camry")},
			{ NAPI.Util.GetHashKey("f40"), new VehicleInfo("Premium Autoroom", 15, 1475000, "f40")},
			{ NAPI.Util.GetHashKey("fordvp"), new VehicleInfo("Premium Autoroom", 25, 1500000, "ford")},
			{ NAPI.Util.GetHashKey("glsvp"), new VehicleInfo("Premium Autoroom", 25, 500000, "gls")},
			{ NAPI.Util.GetHashKey("gs350"), new VehicleInfo("Premium Autoroom", 35, 800000, "350 gs")},
			{ NAPI.Util.GetHashKey("gt17vp"), new VehicleInfo("Premium Autoroom", 25, 1000000, "gt")},
			{ NAPI.Util.GetHashKey("jaguare18"), new VehicleInfo("Premium Autoroom", 15, 1600000, "jaguare")},
			{ NAPI.Util.GetHashKey("lamboreventon"), new VehicleInfo("Premium Autoroom", 15, 3000000, "lamborgini reventon")},
			{ NAPI.Util.GetHashKey("lex570"), new VehicleInfo("Premium Autoroom", 25, 400000, "lexus 570")},
			{ NAPI.Util.GetHashKey("lfa"), new VehicleInfo("Premium Autoroom", 25, 400000, "lfa")},
			{ NAPI.Util.GetHashKey("porsche918"), new VehicleInfo("Premium Autoroom", 35, 1500000, "porsche 918")},
			{ NAPI.Util.GetHashKey("qashqai"), new VehicleInfo("Premium Autoroom", 15, 250000, "qashqai")},
			{ NAPI.Util.GetHashKey("r50"), new VehicleInfo("Premium Autoroom", 15, 1100000, "r50")},
			{ NAPI.Util.GetHashKey("rs6vp"), new VehicleInfo("Premium Autoroom", 25, 700000, "rs 6")},
			{ NAPI.Util.GetHashKey("s15"), new VehicleInfo("Premium Autoroom", 35, 1600000, "s15")},
			{ NAPI.Util.GetHashKey("supragr"), new VehicleInfo("Premium Autoroom", 25, 1700000, "supra gr")},
			{ NAPI.Util.GetHashKey("teslax"), new VehicleInfo("Premium Autoroom", 25, 650000, "tesla x")},
			{ NAPI.Util.GetHashKey("toyotalc200"), new VehicleInfo("Premium Autoroom", 15, 1400000, "toyota prado 200")},
			{ NAPI.Util.GetHashKey("turbos911"), new VehicleInfo("Premium Autoroom", 25, 1000000, "turbo s 911")},
			{ NAPI.Util.GetHashKey("wraithb"), new VehicleInfo("Premium Autoroom", 35, 2000000, "wraith")},
			{ NAPI.Util.GetHashKey("x5g05"), new VehicleInfo("Premium Autoroom", 15, 1500000, "x5 g05")},
			{ NAPI.Util.GetHashKey("x6m"), new VehicleInfo("Premium Autoroom", 15, 2000000, "x6 m")},
			{ NAPI.Util.GetHashKey("z4vp"), new VehicleInfo("Premium Autoroom", 15, 1650000, "z4")},
			{ NAPI.Util.GetHashKey("panamera"), new VehicleInfo("Premium Autoroom", 15, 0, "panamera")},
			{ NAPI.Util.GetHashKey("escalade900"), new VehicleInfo("Premium Autoroom", 15, 1800000, "escalade")},
			{ NAPI.Util.GetHashKey("diablosv"), new VehicleInfo("Premium Autoroom", 25, 1100000, "diablo sv")},
			{ NAPI.Util.GetHashKey("db11"), new VehicleInfo("Premium Autoroom", 15, 1500000, "db 11")},
			{ NAPI.Util.GetHashKey("c7"), new VehicleInfo("Premium Autoroom", 25, 850000, "c7")},
            { NAPI.Util.GetHashKey("dodgeviper"), new VehicleInfo("Premium Autoroom", 35, 1500000, "dodge viper")},
            { NAPI.Util.GetHashKey("bmwx5"), new VehicleInfo("Premium Autoroom", 15, 250000, "bmw x5")},
            { NAPI.Util.GetHashKey("bentleyc"), new VehicleInfo("Premium Autoroom", 15, 1100000, "bentley")},
            { NAPI.Util.GetHashKey("gemera"), new VehicleInfo("Premium Autoroom", 25, 700000, "gemera")},
            { NAPI.Util.GetHashKey("impala67"), new VehicleInfo("Premium Autoroom", 35, 1600000, "impala67")},
            { NAPI.Util.GetHashKey("jeepsrt8"), new VehicleInfo("Premium Autoroom", 25, 1700000, "jeepsrt8")},
            { NAPI.Util.GetHashKey("mbamggt"), new VehicleInfo("Premium Autoroom", 25, 650000, "amg gt")},
            { NAPI.Util.GetHashKey("Camry"), new VehicleInfo("Premium Autoroom", 15, 1400000, "Camry")},
            { NAPI.Util.GetHashKey("Markii"), new VehicleInfo("Premium Autoroom", 25, 1000000, "Markii")},
            { NAPI.Util.GetHashKey("Lexusgsf"), new VehicleInfo("Premium Autoroom", 35, 2000000, "Lexusgsf")},
            { NAPI.Util.GetHashKey("minic"), new VehicleInfo("Premium Autoroom", 15, 1500000, "minic")},
            { NAPI.Util.GetHashKey("RRSVR"), new VehicleInfo("Premium Autoroom", 15, 2000000, "RRSVR")},
            { NAPI.Util.GetHashKey("MBC63S"), new VehicleInfo("Premium Autoroom", 15, 1650000, "MBC63S")},
            { NAPI.Util.GetHashKey("MBE420"), new VehicleInfo("Premium Autoroom", 15, 0, "MBE420")},
            { NAPI.Util.GetHashKey("MBG63"), new VehicleInfo("Premium Autoroom", 15, 1800000, "G63")},
            { NAPI.Util.GetHashKey("MLEvoX"), new VehicleInfo("Premium Autoroom", 25, 1100000, "MLEvoX")},
            { NAPI.Util.GetHashKey("Skyline"), new VehicleInfo("Premium Autoroom", 15, 1500000, "Skyline")},
            { NAPI.Util.GetHashKey("MazdaRX7"), new VehicleInfo("Premium Autoroom", 25, 850000, "MazdaRX7")},
            { NAPI.Util.GetHashKey("NGTR"), new VehicleInfo("Premium Autoroom", 25, 850000, "NGTR")},
            { NAPI.Util.GetHashKey("MBC63"), new VehicleInfo("Premium Autoroom", 25, 850000, "MBC63")},
            { NAPI.Util.GetHashKey("Lambo770"), new VehicleInfo("Premium Autoroom", 25, 850000, "Lambo770")},
            { NAPI.Util.GetHashKey("Ferrari488"), new VehicleInfo("Premium Autoroom", 25, 850000, "Ferrari488")},
            { NAPI.Util.GetHashKey("TeslaS"), new VehicleInfo("Premium Autoroom", 25, 850000, "TeslaS")},
            { NAPI.Util.GetHashKey("Supra"), new VehicleInfo("Premium Autoroom", 25, 850000, "Supra")},
            { NAPI.Util.GetHashKey("SubaruWRX"), new VehicleInfo("Premium Autoroom", 25, 850000, "SubaruWRX")},
            { NAPI.Util.GetHashKey("LX570"), new VehicleInfo("Premium Autoroom", 25, 850000, "LX570")},
            { NAPI.Util.GetHashKey("Lambo580"), new VehicleInfo("Premium Autoroom", 25, 850000, "Lambo580")},
            { NAPI.Util.GetHashKey("Lambo640"), new VehicleInfo("Premium Autoroom", 25, 850000, "Lambo640")},
            { NAPI.Util.GetHashKey("Bentayga"), new VehicleInfo("Premium Autoroom", 25, 850000, "Bentayga")},
            { NAPI.Util.GetHashKey("BmwM3"), new VehicleInfo("Premium Autoroom", 25, 850000, "BmwM3")},
            { NAPI.Util.GetHashKey("BmwI8"), new VehicleInfo("Premium Autoroom", 25, 850000, "BmwI8")},
            { NAPI.Util.GetHashKey("rrcullinan"), new VehicleInfo("Premium Autoroom", 25, 850000, "rrcullinan")},
            { NAPI.Util.GetHashKey("urus"), new VehicleInfo("Premium Autoroom", 25, 850000, "urus")},
            { NAPI.Util.GetHashKey("vapidse"), new VehicleInfo("Premium Autoroom", 25, 850000, "vapidse")},
            { NAPI.Util.GetHashKey("16challenger"), new VehicleInfo("Premium Autoroom", 25, 850000, "16challenger")},
            { NAPI.Util.GetHashKey("silvias15"), new VehicleInfo("Premium Autoroom", 25, 850000, "silvias15")},
            { NAPI.Util.GetHashKey("AudiRS7"), new VehicleInfo("Premium Autoroom", 25, 850000, "AudiRS7")},
            { NAPI.Util.GetHashKey("BMWM5"), new VehicleInfo("Premium Autoroom", 25, 850000, "BMWM5")},
            { NAPI.Util.GetHashKey("BMWX6"), new VehicleInfo("Premium Autoroom", 25, 850000, "BMWX6")},
            { NAPI.Util.GetHashKey("porschegt4"), new VehicleInfo("Premium Autoroom", 25, 850000, "porschegt4")},
            { NAPI.Util.GetHashKey("bmwm8"), new VehicleInfo("Premium Autoroom", 25, 850000, "bmwm8")},
            { NAPI.Util.GetHashKey("sian"), new VehicleInfo("Premium Autoroom", 25, 850000, "sian")},
            { NAPI.Util.GetHashKey("AudiTT"), new VehicleInfo("Premium Autoroom", 25, 850000, "AudiTT")},
            { NAPI.Util.GetHashKey("18rs7"), new VehicleInfo("Premium Autoroom", 25, 850000, "18rs7")},
            { NAPI.Util.GetHashKey("69charger"), new VehicleInfo("Premium Autoroom", 25, 850000, "69charger")},
            { NAPI.Util.GetHashKey("s63amg"), new VehicleInfo("Premium Autoroom", 25, 850000, "s63amg")},
            { NAPI.Util.GetHashKey("brabus700"), new VehicleInfo("Premium Autoroom", 25, 850000, "brabus700")},
            { NAPI.Util.GetHashKey("dl2016"), new VehicleInfo("Premium Autoroom", 25, 850000, "dl2016")},
            { NAPI.Util.GetHashKey("g770"), new VehicleInfo("Premium Autoroom", 25, 850000, "g770")},
            { NAPI.Util.GetHashKey("maybach"), new VehicleInfo("Premium Autoroom", 25, 850000, "maybach")},
            { NAPI.Util.GetHashKey("radiantvff"), new VehicleInfo("Premium Autoroom", 25, 850000, "radiantvff")},


            { NAPI.Util.GetHashKey("Prototipo"), new VehicleInfo("Exotic DonateRoom", 25, 2500000, "Prototipo")},
			{ NAPI.Util.GetHashKey("Tezeract"), new VehicleInfo("Exotic DonateRoom", 25, 2250000, "Tezeract")},
			{ NAPI.Util.GetHashKey("Tyrant"), new VehicleInfo("Exotic DonateRoom", 25, 2250000, "Tyrant")},
			{ NAPI.Util.GetHashKey("Openwheel2"), new VehicleInfo("Exotic DonateRoom", 10, 1500000, "Openwheel2")},
			{ NAPI.Util.GetHashKey("Nero2"), new VehicleInfo("Exotic DonateRoom", 25, 600000, "Nero2")},
			{ NAPI.Util.GetHashKey("Camper"), new VehicleInfo("Exotic DonateRoom", 45, 500000, "Camper")},
			{ NAPI.Util.GetHashKey("Patriot2"), new VehicleInfo("Exotic DonateRoom", 25, 400000, "Patriot2")},
			{ NAPI.Util.GetHashKey("Speedo2"), new VehicleInfo("Exotic DonateRoom", 25, 400000, "Speedo2")},
			{ NAPI.Util.GetHashKey("Journey"), new VehicleInfo("Exotic DonateRoom", 25, 350000, "Journey")},
			{ NAPI.Util.GetHashKey("Vagrant"), new VehicleInfo("Exotic DonateRoom", 5, 1000000, "Journey")},
			{ NAPI.Util.GetHashKey("Veto"), new VehicleInfo("Exotic DonateRoom", 25, 250000, "Veto")},
			{ NAPI.Util.GetHashKey("lp700r"), new VehicleInfo("Exotic Autoroom", 20, 700000, "lp700r")},
			{ NAPI.Util.GetHashKey("g636x6"), new VehicleInfo("Exotic Autoroom", 90, 700000, "g636x6")},
			{ NAPI.Util.GetHashKey("apriora"), new VehicleInfo("Exotic Autoroom", 20, 700000, "apriora")},
			{ NAPI.Util.GetHashKey("ecto1"), new VehicleInfo("Exotic Autoroom", 20, 700000, "ecto1")},
			//
			{ NAPI.Util.GetHashKey("astron"), new VehicleInfo("Elite Autoroom", 25, 700000, "Pfister Astron")},
			{ NAPI.Util.GetHashKey("baller7"), new VehicleInfo("Elite Autoroom", 35, 700000, "Gallivanter Baller ST")},
			{ NAPI.Util.GetHashKey("buffalo4"), new VehicleInfo("Elite Autoroom", 15, 700000, "Bravado Buffalo STX")},
			{ NAPI.Util.GetHashKey("champion"), new VehicleInfo("Elite Autoroom", 15, 700000, "Dewbauchee Champion")},
			{ NAPI.Util.GetHashKey("cinquemila"), new VehicleInfo("Elite Autoroom", 25, 700000, "Lampadati Cinquemila")},
			{ NAPI.Util.GetHashKey("comet7"), new VehicleInfo("Elite Autoroom", 5, 700000, "Pfister Comet S2 Cabrio")},
			{ NAPI.Util.GetHashKey("deity"), new VehicleInfo("Elite Autoroom", 15, 700000, "Enus Deity")},
			{ NAPI.Util.GetHashKey("granger2"), new VehicleInfo("Elite Autoroom", 35, 700000, "Declasse Granger 3600LX")},
			{ NAPI.Util.GetHashKey("ignus"), new VehicleInfo("Elite Autoroom", 25, 700000, "Pegassi Ignus")},
			{ NAPI.Util.GetHashKey("iwagen"), new VehicleInfo("Elite Autoroom", 25, 700000, "Obey I-Wagen")},
			{ NAPI.Util.GetHashKey("jubilee"), new VehicleInfo("Elite Autoroom", 35, 700000, "Enus Jubilee")},
			{ NAPI.Util.GetHashKey("mule5"), new VehicleInfo("Elite Autoroom", 20, 700000, "Maibatsu Mule")},
			{ NAPI.Util.GetHashKey("patriot3"), new VehicleInfo("Elite Autoroom", 35, 700000, "Mammoth Patriot Mil-Spec")},
			{ NAPI.Util.GetHashKey("reever"), new VehicleInfo("Elite Autoroom", 5, 700000, "Western Reever")},
			{ NAPI.Util.GetHashKey("shinobi"), new VehicleInfo("Elite Autoroom", 5, 700000, "Nagasaki Shinobi")},
			{ NAPI.Util.GetHashKey("youga4"), new VehicleInfo("Elite Autoroom", 20, 700000, "Vapid Youga Custom")},
			{ NAPI.Util.GetHashKey("zeno"), new VehicleInfo("Elite Autoroom", 5, 700000, "Overflod Zeno")},
			{ NAPI.Util.GetHashKey("bvit"), new VehicleInfo("Elite Autoroom", 10, 700000, "bvit")},
			{ NAPI.Util.GetHashKey("greenwood"), new VehicleInfo("Low Autoroom", 15, 45000, "c7")},
            { NAPI.Util.GetHashKey("ftype"), new VehicleInfo("Elite Autoroom", 20, 540000, "ftype")},
            { NAPI.Util.GetHashKey("m750li"), new VehicleInfo("Elite Autoroom", 20, 540000, "m750li")},
            { NAPI.Util.GetHashKey("monza"), new VehicleInfo("Elite Autoroom", 20, 540000, "monza")},
            { NAPI.Util.GetHashKey("mysterycar"), new VehicleInfo("Elite Autoroom", 20, 540000, "mysterycar")},



        };

        public static int GetMaxSlots(uint Model)
        {
			try
			{
				if (VehicleData.ContainsKey(Model)) return VehicleData[Model].MaxSlots;
				return Repository.InventoryMaxSlots["vehicle"];
			}
			catch (Exception e)
			{
				Log.Write($"GetMaxSlots Exception: {e.ToString()}");
				return 15;
			}
        }
		public static string GetName(uint Model)
		{
			try
			{
				if (VehicleData.ContainsKey(Model)) return VehicleData[Model].Name;
				return null;
			}
			catch (Exception e)
			{
				Log.Write($"GetName Exception: {e.ToString()}");
				return null;
			}
		}
	}
}
